# "project_id": 636484
# "api_token": ""
# "base_path": ""
# "preserve_hierarchy": true
# "files": [
#   {
#     "source": "src/locales/lang/zh-CN/*.ts",
#     "translation": "src/locales/lang/en/%two_letters_code%/%original_file_name%",
#   }
# ]
project_id: 636484
api_token: 2fad15f0d2925d8123892f8c975dda8994e9c32f85ad19797202295cfc9203f2c40563356b8e50b8
preserve_hierarchy: true
files:
  - source: src/locales/lang/zh-CN/*.ts
    translation: src/locales/lang/en/%two_letters_code%/%original_file_name%