/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    BaseFunctionButton: typeof import('./../src/components/baseComponents/BaseFunctionButton.vue')['default']
    BasicComponent: typeof import('./../src/components/baseComponents/BasicComponent.vue')['default']
    CustomComponent: typeof import('./../src/components/customComponents/CustomComponent.vue')['default']
    'IMingcute:searchLine': typeof import('~icons/mingcute/search-line')['default']
    NavBar: typeof import('./../src/components/customComponents/home/NavBar.vue')['default']
    NavBarItem: typeof import('./../src/components/customComponents/home/NavBarItem.vue')['default']
    NavBarSearch: typeof import('./../src/components/customComponents/home/NavBarSearch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
