# deploy.yml
name: Deploy to Aliyun OSS
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm install
      - run: npm run build
  deploy:
    needs: build # 设置 deploy job 依赖于 build job
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          username: "root"
          server: "${{ secrets.SERVER }}"
          port: 22
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: "./dist/*"
          remote_path:
          # delete_remote_files: true
          sftpArgs: "-o ConnectTimeout=5"
          password: ${{ secrets.PASSWORD }}

