# deploy.yml
name: Deploy to Aliyun OSS
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        uses: actions/setup-node@v2
        with:
            node-version: 18
      - run: npm install
      - run: npm run build
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: scp pipelines
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.SERVER }}
          user: root
          pass: ${{ secrets.SSH_PRIVATE_KEY }}
          scp: |
            './dist/*' => /usr/local/nginx/html