# deploy.yml
name: Deploy to Aliyun OSS
on:
  pull_request:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        uses: actions/setup-node@v2
        with:
            node-version: 18
      - run: npm install
      - run: npm run build
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: 'root'
          server: '139.196.10.107'
          port: 22
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './dist/*'
          remote_path: /var/www/app/blog
          delete_remote_files: true
          sftpArgs: '-o ConnectTimeout=5'
          password: ${{ secrets.PASSWORD }}